notebooks/prepare_igv_viewer_input.py
notebooks/vcf_merge_subsample_tutorial.py
scripts/publish.sh

Publish to workspace and notebook name instead of bucket location.

Improve publish directive

---

notebooks/byod.py

This notebook includes application logic to join Terra data tables over a column.

Introduce the BYOD featured notebook.

---

scripts/publish.sh

Allow scripts/publish.sh to work within container

---

Makefile

Call scripts/publish.sh from container

---

notebooks/byod.py

Removed the function changes from the other PR and attempted to bring this in align with Brian's notebook format rather than Terra's format. As noted on Slack, due to "reasons" this is technically untested, but as this PR is focused on form rather than function I'd rather get it out there now.

Change in overall format and explanations

---

.gitlab-ci.yml

This adds a gitlab yaml.  All hooks and credentials should be set up.
Depends on #29 .

Automate notebook tests with gitlab.

---

.gitignore
Makefile

Only clean ignored files when generating notebooks

---

Makefile
scripts/run_leo_container.sh

This creates a container per notebook test. If the container already exists, it is killed and relaunched.

Improve docker container handling

---

.gitlab-ci.yml
Makefile
environment
scripts/run_leo_container.sh

Introduce environment variables. This should help keep the build environment more sane.
depends on #47

Introduce environment

---

Makefile

Remove unneeded Make variable

---

Makefile
scripts/run_leo_container.sh

This facilitates future per-notebook leo configs.

Move notebook test execution into script

---

.gitlab-ci.yml
environment
scripts/generate_gitlab_yml.sh

Define an image per GitLab job

---

.gitlab-ci.yml
Makefile
environment
notebooks/workflow_cost_estimator/leo_config
scripts/generate_gitlab_yml.sh
scripts/run_leo_container.sh

This allows notebooks to be tested in specific Leo target
environments.
closes #72

Introduce customizable test Leo config

---

notebooks/GWAS_blood_pressure_p2/main.py
notebooks/GWAS_blood_pressure_p2/requirements.txt

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/TLP-1780)

Make tests pass for GWAS_blood_pressure_p2

---

.gitignore
.gitlab-ci.yml
notebooks/GWAS_blood_pressure_p1/main.py
notebooks/GWAS_blood_pressure_p1/requirements.txt
notebooks/GWAS_blood_pressure_p2/main.py
notebooks/GWAS_blood_pressure_p2/requirements.txt

These are tested and appear fully functional in Terra, however, due to the nature of the second notebook some additional testing is still pending.
Pending:
* herzogification of 13.3 (second notebook)
* herzog-friendly form of section 13.6 (second notebook) 
* just generally checking part 13's output is as expected (second notebook)

Add Beth's GWAS Blood Pressure notebooks

---

.gitlab-ci.yml
notebooks/GWAS_blood_pressure_p1/leo_config
notebooks/GWAS_blood_pressure_p2/leo_config
notebooks/GWAS_blood_pressure_p2/requirements.txt

This tests the GWAS notebooks in Hail Leo containers.

Update Leo config for GWAS notebooks

---

notebooks/GWAS_blood_pressure_p1/main.py
notebooks/GWAS_blood_pressure_p2/main.py

See [Lon's comment here](https://github.com/DataBiosphere/bdcat_notebooks/pull/73#discussion_r542957796). The 1000 Genomes version will be in the new 1000 Genomes PR.

Remove python2 style headers from blood pressure notebooks

---

.gitlab-ci.yml
notebooks/GWAS_1000Genomes_p1/main.py
notebooks/GWAS_1000Genomes_p2/main.py
notebooks/GWAS_1000Genomes_p3/leo_config
notebooks/GWAS_1000Genomes_p3/main.py
notebooks/GWAS_1000Genomes_p3/requirements.txt
notebooks/GWAS_blood_pressure_p3/main.py

plus some miscellanous fixes and organizational changes. Fully tested on Terra; GWAS works with no issues after a quick hotfix to the template workspace's default arguments.

Split the second 1000 Genomes GWAS notebook into two

---

notebooks/GWAS_blood_pressure_p3/main.py

In preparation for some efficiency changes, let's tidy this notebook up, shall we?

Improve readability on third bp GWAS notebook

---

notebooks/workflow_cost_estimator/main.py
notebooks/workflow_cost_estimator/requirements.txt

- Update cost estimator notebook to work with TNU changes
- Drop pandas formatting, which has unfortunately complex formatting

Update workflow cost estimator, remove pandas

---

notebooks/workflow_cost_estimator/publish.txt

New target is [here](https://terra.biodatacatalyst.nhlbi.nih.gov/#workspaces/biodata-catalyst/BioData%20Catalyst%20Collection/notebooks/launch/Workflow%20Cost%20Estimator.ipynb)

Include BDCat collection in cost publish target

---

notebooks/GWAS_1000Genomes_p1/main.py
notebooks/GWAS_1000Genomes_p2/main.py
notebooks/GWAS_1000Genomes_p3/main.py
notebooks/GWAS_blood_pressure_p1/main.py
notebooks/GWAS_blood_pressure_p2/main.py
notebooks/GWAS_blood_pressure_p3/main.py

* Update default to new default
* Adapt to new UI for custom environments
* Make clarifications and rearrange some text
* Adjust ugly spacing in table, even though the user does not see this, because it bothers me

Adjust application configuration in GWAS nbs
